### ISSUE TITLE
[Idea] What if this were a global composer repository?

### ISSUE THREAD

**Issue by tabacitu** [shinokada/backpack_install#1]
This is in no way a must-do, I'm just throwing ideas at the wall here, see what sticks. Might be a bad idea 😅🤷‍♂️

What if... instead of people having to git clone this (or copy-paste the install script) they could do `composer global require shinokada/backpack-addons-installer`? The way I see it, that would:
- be similar to [the official Laravel installer](https://github.com/laravel/installer)
- make it easier to get updates to the script (when they do `composer global update`)
- make it easier to use (a global command that would run the script for the current directory, eg. `backpack:addons`)

So the entire process to set up a new Laravel + Backpack install could become:
```bash
# STEP 1 - Regular Laravel app setup
laravel new project-name
cd project-name
# Todo: configure the .env, create a db, start the server if needed, etc

# STEP 2 - Install Backpack
backpack install
# at the end it would ask if you want to also install some addons, if so it'll run `backpack addons`
# which would go down the addons list and ask what you want installed and do it
```

So for Mac OS + Laravel Valet for example, if you _do_ use [Laravel Lambo](https://github.com/tighten/lambo) + this as a global composer repository, the whole process would be: 
```bash
cd ~/Sites
lambo new some-project
cd some-project
backpack install
```

😀 Wouldn't that be great? 'could be overkill though, if not enough people have this need 🤷‍♂️ And it'd only be this magical for people who can use Laravel Lambo, which is MacOS + Valet users. What do you think @shinokada ? 

@pxpm ? @promatik ? What do you guys use to set up new projects? Is there anything like Lambo for Windows?

**Comment by shinokada** [comment]
That's a great idea.
I will check out how the composer works.

**Comment by promatik** [comment]
> What do you guys use to set up new projects? Is there anything like Lambo for Windows?

I'm not an example 😅 I have a very own way to create new projects.

I have two repos, `laravel-boilerplate` and `laravel-framework`. Basically the boilerplate is a clean project with everything already installed, (laravel + backpack + framework), the framework has useful stuff like helpers, commands, and enhancements to backpack/admin panel, common stuff like a flag picker to change language or a cache management interface.

Then I have a command to "clone" the boilerplate and there it is, a new project without any setups.
I have to update everything once in a while and check everything's working But since we create a lot admin panels where I work, this way is the easiest.

---

Anyway, this method arose exactly because the installation process was painful 😅
So I TOTALY support an easier installation process ✌

**Comment by shinokada** [comment]
Close this for now.
Let me know if you want to reopen.
